version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - automation
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - automation
      - dependencies
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    cooldown:
      default-days: 10
