(library
 (name base_ui)
 (public_name base_ui)
 (modules
  base_ui
  accordion
  alert_dialog
  autocomplete
  avatar
  button
  checkbox
  checkbox_group
  collapsible
  combobox
  context_menu
  dialog
  drawer
  field
  fieldset
  form
  input
  menu
  menubar
  meter
  navigation_menu
  number_field
  otp_field
  popover
  preview_card
  progress
  radio
  radio_group
  scroll_area
  select
  separator
  slider
  switch
  tabs
  toast
  toggle
  toggle_group
  toolbar
  tooltip)
 (modes melange)
 (preprocess
  (pps melange.ppx reason-react-ppx))
 (libraries reason-react))
