// Generated by Melange

import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

function App$App(Props) {
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsx("h1", {
      children: "Hello, React.ml!"
    })
  });
}

const App = {
  make: App$App
};

const element = document.querySelector("#root");

if (element == null) {
  console.error("Failed to start React: couldn't find the #root element");
} else {
  const root = Client.createRoot(element);
  root.render(JsxRuntime.jsx(App$App, {}));
}

export {
  App,
}
/* element Not a pure module */
